In [4]:
import pandas as pd
from pathlib import Path

In [5]:
data_path = Path("../data/raw")
files = sorted(data_path.glob("yellow_tripdata_*.parquet"))
files

[WindowsPath('../data/raw/yellow_tripdata_2026-01.parquet'),
 WindowsPath('../data/raw/yellow_tripdata_2026-02.parquet'),
 WindowsPath('../data/raw/yellow_tripdata_2026-03.parquet'),
 WindowsPath('../data/raw/yellow_tripdata_2026-04.parquet'),
 WindowsPath('../data/raw/yellow_tripdata_2026-05.parquet')]

In [6]:
df = pd.concat([pd.read_parquet(file) for file in files], ignore_index=True)

In [7]:
df.shape

(18999282, 20)

In [8]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18999282 entries, 0 to 18999281
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), object(1)
memory usage: 2.6+ GB

In [10]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,1.899928e+07,18999282,18999282,1.418700e+07,1.899928e+07,1.418700e+07,1.899928e+07,1.899928e+07,1.899928e+07,1.899928e+07,1.899928e+07,1.899928e+07,1.899928e+07,1.899928e+07,1.899928e+07,1.899928e+07,1.418700e+07,1.418700e+07,1.899928e+07
mean,1.875830e+00,2026-03-19 01:29:42.917016,2026-03-19 01:47:33.015019,1.241392e+00,5.738800e+00,5.498504e+00,1.617346e+02,1.612376e+02,8.690561e-01,2.127290e+01,1.091794e+00,4.878450e-01,2.822783e+00,5.176971e-01,9.524978e-01,2.998400e+01,2.184174e+00,1.560088e-01,5.192981e-01
min,1.000000e+00,2001-01-01 09:23:58,2001-01-01 16:09:38,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-2.555200e+03,-7.500000e+00,-5.000000e-01,-2.220000e+02,-1.117900e+02,-1.000000e+00,-2.560200e+03,-2.500000e+00,-2.000000e+00,-7.500000e-01
25%,2.000000e+00,2026-02-08 19:39:41,2026-02-08 19:56:11,1.000000e+00,1.010000e+00,1.000000e+00,1.140000e+02,1.070000e+02,0.000000e+00,1.000000e+01,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.734000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2026-03-19 09:52:15.500000,2026-03-19 10:10:54.500000,1.000000e+00,1.830000e+00,1.000000e+00,1.610000e+02,1.620000e+02,1.000000e+00,1.560000e+01,0.000000e+00,5.000000e-01,2.000000e+00,0.000000e+00,1.000000e+00,2.358000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2026-04-25 20:05:33,2026-04-25 20:22:51,1.000000e+00,3.750000e+00,1.000000e+00,2.330000e+02,2.340000e+02,1.000000e+00,2.680000e+01,2.500000e+00,5.000000e-01,3.970000e+00,0.000000e+00,1.000000e+00,3.471000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2026-06-01 00:20:35,2026-06-02 12:53:42,9.000000e+00,3.285222e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,5.525990e+03,2.071000e+01,1.050000e+01,7.660000e+02,1.400000e+03,2.500000e+00,5.530740e+03,2.500000e+00,2.700000e+01,7.500000e-01
std,7.196782e-01,NaN,NaN,6.447851e-01,5.691660e+02,2.029382e+01,6.685849e+01,7.081129e+01,6.480187e-01,1.871006e+01,1.737200e+00,9.438537e-02,3.934168e+00,2.176932e+00,2.391418e-01,2.245494e+01,8.782616e-01,5.587138e-01,3.525776e-01

In [11]:
df.isnull().sum()

VendorID                       0
tpep_pickup_datetime           0
tpep_dropoff_datetime          0
passenger_count          4812280
trip_distance                  0
RatecodeID               4812280
store_and_fwd_flag       4812280
PULocationID                   0
DOLocationID                   0
payment_type                   0
fare_amount                    0
extra                          0
mta_tax                        0
tip_amount                     0
tolls_amount                   0
improvement_surcharge          0
total_amount                   0
congestion_surcharge     4812280
Airport_fee              4812280
cbd_congestion_fee             0
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')

In [14]:
df.memory_usage(deep=True).sum() / 1024**2

3431.5494956970215

In [15]:
# Save merged dataset
output_path = Path("../data/processed")
output_path.mkdir(parents=True, exist_ok=True)

df.to_parquet(output_path / "merged_taxi_data.parquet", index=False)

In [16]:
# Check data types
df.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

In [17]:
# Count unique values in categorical columns
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

store_and_fwd_flag
store_and_fwd_flag
N    14171108
Y       15894
Name: count, dtype: int64

In [18]:
# Remove duplicate rows (if any)
df = df.drop_duplicates()

In [19]:
# Convert pickup and dropoff to datetime
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])
df["tpep_dropoff_datetime"] = pd.to_datetime(df["tpep_dropoff_datetime"])

In [20]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')

In [21]:
# Missing values
df.isnull().sum()

VendorID                       0
tpep_pickup_datetime           0
tpep_dropoff_datetime          0
passenger_count          4812280
trip_distance                  0
RatecodeID               4812280
store_and_fwd_flag       4812280
PULocationID                   0
DOLocationID                   0
payment_type                   0
fare_amount                    0
extra                          0
mta_tax                        0
tip_amount                     0
tolls_amount                   0
improvement_surcharge          0
total_amount                   0
congestion_surcharge     4812280
Airport_fee              4812280
cbd_congestion_fee             0
dtype: int64

In [22]:
# Remove rows with missing pickup/dropoff times
df = df.dropna(subset=["tpep_pickup_datetime", "tpep_dropoff_datetime"])

In [23]:
# Remove invalid passenger counts
df = df[df["passenger_count"] > 0]

In [24]:
# Remove invalid trip distances
df = df[df["trip_distance"] > 0]

In [25]:
# Remove trips with non-positive fares
df = df[df["fare_amount"] > 0]

In [26]:
# Remove trips where dropoff is before pickup
df = df[df["tpep_dropoff_datetime"] > df["tpep_pickup_datetime"]]

In [27]:
# Check remaining shape
df.shape

(13613186, 20)

In [28]:
df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
cbd_congestion_fee       0
dtype: int64

FEATURE ENG

In [29]:
# Trip duration (minutes)
df["trip_duration_min"] = (
    df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]
).dt.total_seconds() / 60

In [30]:
# Remove unrealistic durations
df = df[(df["trip_duration_min"] > 0) & (df["trip_duration_min"] <= 180)]

In [31]:
# Extract time features
df["pickup_hour"] = df["tpep_pickup_datetime"].dt.hour
df["pickup_day"] = df["tpep_pickup_datetime"].dt.day
df["pickup_month"] = df["tpep_pickup_datetime"].dt.month
df["pickup_dayofweek"] = df["tpep_pickup_datetime"].dt.dayofweek

In [32]:
# Weekend flag
df["is_weekend"] = df["pickup_dayofweek"].isin([5, 6]).astype(int)

In [33]:

df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,trip_duration_min,pickup_hour,pickup_day,pickup_month,pickup_dayofweek,is_weekend
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,...,15.86,2.5,0.0,0.00,5.550000,0,1,1,3,0
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,...,55.56,2.5,0.0,0.75,42.800000,0,1,1,3,0
5,2,2026-01-01 00:47:11,2026-01-01 01:00:47,2.0,2.33,1.0,N,144,137,1,...,24.94,2.5,0.0,0.75,13.600000,0,1,1,3,0
6,1,2026-01-01 00:17:54,2026-01-01 00:28:32,1.0,1.30,1.0,N,142,50,2,...,17.15,2.5,0.0,0.75,10.633333,0,1,1,3,0
8,2,2026-01-01 00:34:14,2026-01-01 01:11:58,1.0,5.34,1.0,N,161,45,1,...,51.66,2.5,0.0,0.75,37.733333,0,1,1,3,0

In [35]:
output_path=Path("../data/processed")
output_path.mkdir(parents=True,exist_ok=True)
df.to_parquet(output_path/"cleaned_taxi_data.parquet",index=False)

In [ ]:
## Savinf up anoher file for less memeroy invovlement 
demand_df = df[["PULocationID", "tpep_pickup_datetime"]]

demand_df.to_parquet("../data/processed/demand_data.parquet",index=False)

# 01. Data Loading & Initial Preprocessing

## Objectives
- Load all monthly NYC Yellow Taxi trip datasets.
- Merge them into a single DataFrame.
- Perform initial data inspection.
- Clean invalid and inconsistent records.
- Create basic time-based features.
- Save the cleaned dataset for later stages.

---

## Steps Performed

### 1. Imported Libraries
- pandas
- pathlib

### 2. Located Dataset Files
- Used `Path` and `glob()` to automatically detect all monthly Parquet files.

### 3. Loaded and Merged Data
- Read all Parquet files.
- Combined them into a single DataFrame.

### 4. Initial Inspection
- Dataset shape
- First few rows
- Data types
- Summary statistics
- Missing values
- Duplicate rows
- Memory usage
- Column names

### 5. Data Cleaning
- Removed duplicate records.
- Removed rows with missing pickup/dropoff timestamps.
- Removed trips with:
  - Passenger count ≤ 0
  - Trip distance ≤ 0
  - Fare amount ≤ 0
  - Dropoff time before pickup time

### 6. Feature Engineering
Created:
- Trip Duration (minutes)
- Pickup Hour
- Pickup Day
- Pickup Month
- Pickup Day of Week
- Weekend Indicator

### 7. Saved Processed Data
- Exported the cleaned dataset as:
  `data/processed/cleaned_taxi_data.parquet`

---

## Output

A cleaned taxi trip dataset ready for Exploratory Data Analysis (EDA).