In [1]:
import pandas as pd
from pathlib import Path

In [6]:
df = pd.read_parquet("../data/processed/demand_data.parquet")

In [7]:
df["pickup_hour_timestamp"] = df["tpep_pickup_datetime"].dt.floor("h")

In [8]:
demand_df = (df.groupby(["PULocationID", "pickup_hour_timestamp"]).size().reset_index(name="demand"))

In [9]:
demand_df.head()

   PULocationID pickup_hour_timestamp  demand
0             1   2026-01-01 05:00:00       1
1             1   2026-01-01 11:00:00       1
2             1   2026-01-01 12:00:00       1
3             1   2026-01-01 15:00:00       2
4             1   2026-01-01 17:00:00       2

In [10]:
demand_df.shape

(462305, 3)

In [12]:
demand_df["date"] = demand_df["pickup_hour_timestamp"].dt.date
demand_df["hour"] = demand_df["pickup_hour_timestamp"].dt.hour
demand_df["day_of_week"] = demand_df["pickup_hour_timestamp"].dt.dayofweek
demand_df["month"] = demand_df["pickup_hour_timestamp"].dt.month
demand_df["is_weekend"] = demand_df["day_of_week"].isin([5, 6]).astype(int)

In [13]:
demand_df.head()

,PULocationID,pickup_hour_timestamp,demand,date,hour,day_of_week,month,is_weekend
0,1,2026-01-01 05:00:00,1,2026-01-01,5,3,1,0
1,1,2026-01-01 11:00:00,1,2026-01-01,11,3,1,0
2,1,2026-01-01 12:00:00,1,2026-01-01,12,3,1,0
3,1,2026-01-01 15:00:00,2,2026-01-01,15,3,1,0
4,1,2026-01-01 17:00:00,2,2026-01-01,17,3,1,0

In [ ]:
demand_df.to_parquet("../data/processed/hourly_demand.parquet",index=FalseS)

# 03. Demand Aggregation

## Objectives
- Transform trip-level data into an hourly demand forecasting dataset.
- Create the target variable (`demand`) for machine learning.
- Generate basic time-based features.
- Save the aggregated dataset for feature engineering.

---

## Steps Performed

### 1. Loaded Processed Data
- Imported the cleaned demand dataset containing:
  - `PULocationID`
  - `tpep_pickup_datetime`

### 2. Rounded Pickup Time
- Rounded each pickup timestamp to the nearest hour using:

```python
dt.floor("h")
```

- Created:
  - `pickup_hour_timestamp`

This groups all trips occurring within the same hour.

---

### 3. Created Target Variable

Grouped data by:

- Pickup Location ID
- Pickup Hour

Then counted the number of trips.

```python
groupby(["PULocationID", "pickup_hour_timestamp"]).size()
```

Created:

- `demand`

This represents:

> Number of taxi pickups in a particular zone during a specific hour.

This is the prediction target for the ML model.

---

### 4. Created Time Features

Extracted:

- Date
- Hour
- Day of Week
- Month
- Weekend Indicator

These features help the model learn temporal demand patterns.

---

### 5. Saved Aggregated Dataset

Saved the final dataset as:

```
data/processed/hourly_demand.parquet
```

---

## Output

A structured hourly demand dataset where each row represents:

- Pickup Zone
- Pickup Hour
- Hourly Demand
- Time-based Features

This dataset is now ready for advanced feature engineering and machine learning model development.